package com.bjpowernode.crm.workbench.mapper;

import com.bjpowernode.crm.workbench.domain.Clue;
import com.bjpowernode.crm.workbench.domain.ClueActivityRelation;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface ClueActivityRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue_activity_relation
     *
     * @mbggenerated Mon Sep 04 13:25:50 CST 2023
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue_activity_relation
     *
     * @mbggenerated Mon Sep 04 13:25:50 CST 2023
     */
    int insert(ClueActivityRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue_activity_relation
     *
     * @mbggenerated Mon Sep 04 13:25:50 CST 2023
     */
    int insertSelective(ClueActivityRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue_activity_relation
     *
     * @mbggenerated Mon Sep 04 13:25:50 CST 2023
     */
    ClueActivityRelation selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue_activity_relation
     *
     * @mbggenerated Mon Sep 04 13:25:50 CST 2023
     */
    int updateByPrimaryKeySelective(ClueActivityRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue_activity_relation
     *
     * @mbggenerated Mon Sep 04 13:25:50 CST 2023
     */
    int updateByPrimaryKey(ClueActivityRelation record);

    /*
    * 批量保存
    * */
    int insertClueActivityRelationList(List<ClueActivityRelation> clueActivityRelations);

    /*
    * 根据活动Id和线索Id删除关联信息
    * */
    int deleteClueActivityRelationByClueIdActivityId(ClueActivityRelation clueActivityRelation);

    List<ClueActivityRelation> selectClueActivityRelationByClueId(String clueId);

    int deleteClueActivityRelationByClueId(String clueId);

}